version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "nadyagrishina"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps"